package name.huangzhoujin.mymaven.persistence.domain;

import java.io.Serializable;
import java.util.Date;

public class Repository implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MVN_REPOSITORY.REP_ID
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    private Integer repId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MVN_REPOSITORY.REP_URL
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    private String repUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MVN_REPOSITORY.LAST_UPDATED
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MVN_REPOSITORY.USED_FLAG
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    private String usedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MVN_REPOSITORY
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MVN_REPOSITORY.REP_ID
     *
     * @return the value of T_MVN_REPOSITORY.REP_ID
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    public Integer getRepId() {
        return repId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MVN_REPOSITORY.REP_ID
     *
     * @param repId the value for T_MVN_REPOSITORY.REP_ID
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    public void setRepId(Integer repId) {
        this.repId = repId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MVN_REPOSITORY.REP_URL
     *
     * @return the value of T_MVN_REPOSITORY.REP_URL
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    public String getRepUrl() {
        return repUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MVN_REPOSITORY.REP_URL
     *
     * @param repUrl the value for T_MVN_REPOSITORY.REP_URL
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    public void setRepUrl(String repUrl) {
        this.repUrl = repUrl == null ? null : repUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MVN_REPOSITORY.LAST_UPDATED
     *
     * @return the value of T_MVN_REPOSITORY.LAST_UPDATED
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MVN_REPOSITORY.LAST_UPDATED
     *
     * @param lastUpdated the value for T_MVN_REPOSITORY.LAST_UPDATED
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MVN_REPOSITORY.USED_FLAG
     *
     * @return the value of T_MVN_REPOSITORY.USED_FLAG
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    public String getUsedFlag() {
        return usedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MVN_REPOSITORY.USED_FLAG
     *
     * @param usedFlag the value for T_MVN_REPOSITORY.USED_FLAG
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    public void setUsedFlag(String usedFlag) {
        this.usedFlag = usedFlag == null ? null : usedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MVN_REPOSITORY
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Repository other = (Repository) that;
        return (this.getRepId() == null ? other.getRepId() == null : this.getRepId().equals(other.getRepId()))
            && (this.getRepUrl() == null ? other.getRepUrl() == null : this.getRepUrl().equals(other.getRepUrl()))
            && (this.getLastUpdated() == null ? other.getLastUpdated() == null : this.getLastUpdated().equals(other.getLastUpdated()))
            && (this.getUsedFlag() == null ? other.getUsedFlag() == null : this.getUsedFlag().equals(other.getUsedFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MVN_REPOSITORY
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRepId() == null) ? 0 : getRepId().hashCode());
        result = prime * result + ((getRepUrl() == null) ? 0 : getRepUrl().hashCode());
        result = prime * result + ((getLastUpdated() == null) ? 0 : getLastUpdated().hashCode());
        result = prime * result + ((getUsedFlag() == null) ? 0 : getUsedFlag().hashCode());
        return result;
    }
}