SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE T_MVN_REPOSITORY;




/* Create Tables */

CREATE TABLE T_MVN_REPOSITORY
(
	REP_ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	REP_URL VARCHAR(1024) NOT NULL,
	LAST_UPDATED TIMESTAMP DEFAULT NOW() NOT NULL,
	USED_FLAG CHAR(1) DEFAULT 'N' NOT NULL,
	PRIMARY KEY (REP_ID)
);



