
/* Drop Indexes */

DROP INDEX IDX_DA_PROVINCE ON T_DA_PROVINCE;



/* Drop Tables */

DROP TABLE T_DAT_CONTACT;
DROP TABLE T_DA_SUPPLIERPRODUCT;
DROP TABLE T_DA_PRODUCTBRAND;
DROP TABLE T_DA_BRAND;
DROP TABLE T_DA_PRODUCT;
DROP TABLE T_DA_CATEGORY;
DROP TABLE T_DA_SUPPLIER;
DROP TABLE T_DA_CITY;
DROP TABLE T_DA_COMMODITY;
DROP TABLE T_DA_COUNTRY;
DROP TABLE T_DA_PROVINCE;




/* Create Tables */

-- 联系方法表
CREATE TABLE T_DAT_CONTACT
(
	CONTACT_ID INT NOT NULL AUTO_INCREMENT,
	CONTACT_CONTENT VARCHAR(30) NOT NULL,
	-- 联系方式: Q:qq, T: telphone, E: email, M: mobile
	CONTACT_TYPE CHAR(1) DEFAULT 'Q' NOT NULL COMMENT '联系方式: Q:qq, T: telphone, E: email, M: mobile',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) NOT NULL COMMENT '激活标志位',
	SUPPLIER_ID INT NOT NULL,
	PRIMARY KEY (CONTACT_ID)
) COMMENT = '联系方法表';


-- 品牌信息表
CREATE TABLE T_DA_BRAND
(
	-- 品牌系统主键
	BRAND_ID INT NOT NULL AUTO_INCREMENT COMMENT '品牌系统主键',
	-- 品牌中文名
	BRAND_NAME VARCHAR(20) NOT NULL COMMENT '品牌中文名',
	-- 品牌英文名
	BRAND_ENGLISH VARCHAR(20) NOT NULL COMMENT '品牌英文名',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) DEFAULT 'N' NOT NULL COMMENT '激活标志位',
	COUNTRY_ID INT NOT NULL,
	PRIMARY KEY (BRAND_ID)
) COMMENT = '品牌信息表';


-- 产品类别信息表
CREATE TABLE T_DA_CATEGORY
(
	-- 产品类别名系统主键
	CATEGORY_ID INT NOT NULL AUTO_INCREMENT COMMENT '产品类别名系统主键',
	-- 产品类别中文名
	CATEGORY_NAME VARCHAR(20) NOT NULL COMMENT '产品类别中文名',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) DEFAULT 'N' NOT NULL COMMENT '激活标志位',
	PRIMARY KEY (CATEGORY_ID)
) COMMENT = '产品类别信息表';


-- 城市信息表，记录中城市的基本信息。
CREATE TABLE T_DA_CITY
(
	-- 城市系统主键
	CITY_ID INT NOT NULL AUTO_INCREMENT COMMENT '城市系统主键',
	-- 城市中文名
	CITY_NAME VARCHAR(20) NOT NULL COMMENT '城市中文名',
	CITY_ABBREVIATION VARCHAR(3),
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) COMMENT '激活标志位',
	-- 省份的系统主键
	PROVINCE_ID INT NOT NULL COMMENT '省份的系统主键',
	PRIMARY KEY (CITY_ID)
) COMMENT = '城市信息表，记录中城市的基本信息。';


CREATE TABLE T_DA_COMMODITY
(
	COMMODITY_ID INT NOT NULL AUTO_INCREMENT,
	COMMODITY_NAME VARCHAR(30) NOT NULL,
	COMMODITY_DESCRIPTION VARCHAR(3000) NOT NULL,
	COMMODITY_IMAGE BLOB NOT NULL,
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) NOT NULL COMMENT '激活标志位',
	START_DATE DATETIME,
	END_DATE DATETIME,
	PRIMARY KEY (COMMODITY_ID)
);


CREATE TABLE T_DA_COUNTRY
(
	COUNTRY_ID INT NOT NULL AUTO_INCREMENT,
	-- 国家中文名
	COUNTRY_NAME VARCHAR(30) NOT NULL COMMENT '国家中文名',
	-- 国家名字母缩写
	COUNTRY_ABBREVIATION VARCHAR(5) NOT NULL COMMENT '国家名字母缩写',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) DEFAULT 'N' NOT NULL COMMENT '激活标志位',
	PRIMARY KEY (COUNTRY_ID)
);


-- 产品信息表
CREATE TABLE T_DA_PRODUCT
(
	-- 产品系统主键
	PRODUCT_ID INT NOT NULL AUTO_INCREMENT COMMENT '产品系统主键',
	-- 产品中文名
	PRODUCT_NAME VARCHAR(20) NOT NULL COMMENT '产品中文名',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) DEFAULT 'N' NOT NULL COMMENT '激活标志位',
	-- 产品类别名系统主键
	CATEGORY_ID INT NOT NULL COMMENT '产品类别名系统主键',
	PRIMARY KEY (PRODUCT_ID)
) COMMENT = '产品信息表';


-- 品牌产品信息表
CREATE TABLE T_DA_PRODUCTBRAND
(
	-- 品牌产品系统主键
	PRODUCTBRAND_ID INT NOT NULL AUTO_INCREMENT COMMENT '品牌产品系统主键',
	-- 品牌系统主键
	BRAND_ID INT NOT NULL COMMENT '品牌系统主键',
	-- 产品系统主键
	PRODUCT_ID INT NOT NULL COMMENT '产品系统主键',
	-- 创建者
	CREATED_BY VARCHAR(30) COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) COMMENT '激活标志位',
	PRIMARY KEY (PRODUCTBRAND_ID)
) COMMENT = '品牌产品信息表';


-- 省份信息表，记录中国每个省的基本信息。
CREATE TABLE T_DA_PROVINCE
(
	-- 省份的系统主键
	PROVINCE_ID INT NOT NULL AUTO_INCREMENT COMMENT '省份的系统主键',
	-- 省份的中文名称；如辽宁省等
	PROVINCE_NAME VARCHAR(20) NOT NULL COMMENT '省份的中文名称；如辽宁省等',
	-- 省份的字母缩写,如辽宁省为LN,均为大写
	PROVINCE_ABBREVIATION VARCHAR(3) NOT NULL COMMENT '省份的字母缩写,如辽宁省为LN,均为大写',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) DEFAULT 'N' NOT NULL COMMENT '激活标志位',
	PRIMARY KEY (PROVINCE_ID)
) ENGINE = InnoDB COMMENT = '省份信息表，记录中国每个省的基本信息。' DEFAULT CHARACTER SET utf8;


-- 代理商信息，没有完成.
CREATE TABLE T_DA_SUPPLIER
(
	SUPPLIER_ID INT NOT NULL AUTO_INCREMENT,
	SUPPLIER_NAME VARCHAR(20),
	-- 城市系统主键
	CITY_ID INT NOT NULL COMMENT '城市系统主键',
	-- 创建者
	CREATED_BY VARCHAR(30) COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) COMMENT '激活标志位',
	PRIMARY KEY (SUPPLIER_ID)
) COMMENT = '代理商信息，没有完成.';


CREATE TABLE T_DA_SUPPLIERPRODUCT
(
	SUPPLIER_ID INT NOT NULL,
	-- 品牌产品系统主键
	PRODUCTBRAND_ID INT NOT NULL COMMENT '品牌产品系统主键',
	PRIMARY KEY (SUPPLIER_ID, PRODUCTBRAND_ID)
);



/* Create Foreign Keys */

ALTER TABLE T_DA_PRODUCTBRAND
	ADD FOREIGN KEY (BRAND_ID)
	REFERENCES T_DA_BRAND (BRAND_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_PRODUCT
	ADD FOREIGN KEY (CATEGORY_ID)
	REFERENCES T_DA_CATEGORY (CATEGORY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_SUPPLIER
	ADD FOREIGN KEY (CITY_ID)
	REFERENCES T_DA_CITY (CITY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_BRAND
	ADD FOREIGN KEY (COUNTRY_ID)
	REFERENCES T_DA_COUNTRY (COUNTRY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_PRODUCTBRAND
	ADD FOREIGN KEY (PRODUCT_ID)
	REFERENCES T_DA_PRODUCT (PRODUCT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_SUPPLIERPRODUCT
	ADD FOREIGN KEY (PRODUCTBRAND_ID)
	REFERENCES T_DA_PRODUCTBRAND (PRODUCTBRAND_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_CITY
	ADD FOREIGN KEY (PROVINCE_ID)
	REFERENCES T_DA_PROVINCE (PROVINCE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DAT_CONTACT
	ADD FOREIGN KEY (SUPPLIER_ID)
	REFERENCES T_DA_SUPPLIER (SUPPLIER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_SUPPLIERPRODUCT
	ADD FOREIGN KEY (SUPPLIER_ID)
	REFERENCES T_DA_SUPPLIER (SUPPLIER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Create Indexes */

CREATE INDEX IDX_DA_PROVINCE USING BTREE ON T_DA_PROVINCE (PROVINCE_ID ASC);



