
/* Drop Indexes */

DROP INDEX IDX_DA_PROVINCE_ID ON T_DA_PROVINCE;



/* Drop Tables */

DROP TABLE T_DA_SUPPLIERPRODUCT;
DROP TABLE T_DA_PRODUCTBRAND;
DROP TABLE T_DA_BRAND;
DROP TABLE T_DA_PRODUCT;
DROP TABLE T_DA_CATEGORY;
DROP TABLE T_DA_CONTACT;
DROP TABLE T_DA_SUPPLIER;
DROP TABLE T_DA_CITY;
DROP TABLE T_DA_COMMODITYIMAGE;
DROP TABLE T_DA_COMMODITY;
DROP TABLE T_DA_COUNTRY;
DROP TABLE T_DA_HISTORY;
DROP TABLE T_DA_PROVINCE;
DROP TABLE T_DA_USERROLE;
DROP TABLE T_DA_ROLE;
DROP TABLE T_DA_SEQUENCE;
DROP TABLE T_DA_USER;




/* Create Tables */

-- 品牌信息表
CREATE TABLE T_DA_BRAND
(
	-- 品牌系统主键
	BRAND_ID INT NOT NULL AUTO_INCREMENT COMMENT '品牌系统主键',
	-- 品牌中文名
	BRAND_NAME VARCHAR(20) NOT NULL COMMENT '品牌中文名',
	-- 品牌英文名
	BRAND_ENGLISH VARCHAR(20) NOT NULL COMMENT '品牌英文名',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) DEFAULT 'N' NOT NULL COMMENT '激活标志位',
	-- 国家信息的系统主键
	COUNTRY_ID INT NOT NULL COMMENT '国家信息的系统主键',
	PRIMARY KEY (BRAND_ID)
) ENGINE = InnoDB COMMENT = '品牌信息表' DEFAULT CHARACTER SET utf8;


-- 产品类别信息表
CREATE TABLE T_DA_CATEGORY
(
	-- 产品类别名系统主键
	CATEGORY_ID INT NOT NULL AUTO_INCREMENT COMMENT '产品类别名系统主键',
	-- 产品类别中文名
	CATEGORY_NAME VARCHAR(20) NOT NULL COMMENT '产品类别中文名',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) DEFAULT 'N' NOT NULL COMMENT '激活标志位',
	PRIMARY KEY (CATEGORY_ID)
) ENGINE = InnoDB COMMENT = '产品类别信息表' DEFAULT CHARACTER SET utf8;


-- 城市信息表，记录中城市的基本信息。
CREATE TABLE T_DA_CITY
(
	-- 城市系统主键
	CITY_ID INT NOT NULL AUTO_INCREMENT COMMENT '城市系统主键',
	-- 城市中文名
	CITY_NAME VARCHAR(20) NOT NULL COMMENT '城市中文名',
	-- 城市缩写(如大连,DL)
	CITY_ABBREVIATION VARCHAR(5) COMMENT '城市缩写(如大连,DL)',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) DEFAULT 'N' COMMENT '激活标志位',
	-- 省份的系统主键
	PROVINCE_ID INT NOT NULL COMMENT '省份的系统主键',
	PRIMARY KEY (CITY_ID)
) ENGINE = InnoDB COMMENT = '城市信息表，记录中城市的基本信息。' DEFAULT CHARACTER SET utf8;


-- 商品信息表
CREATE TABLE T_DA_COMMODITY
(
	-- 商品系统主键
	COMMODITY_ID INT NOT NULL AUTO_INCREMENT COMMENT '商品系统主键',
	-- 商品名称
	COMMODITY_NAME VARCHAR(30) NOT NULL COMMENT '商品名称',
	-- 商品介绍
	COMMODITY_DESCRIPTION VARCHAR(3000) NOT NULL COMMENT '商品介绍',
	-- 有效期开始时间
	START_DATE DATETIME COMMENT '有效期开始时间',
	-- 有效期结束时间
	END_DATE DATETIME COMMENT '有效期结束时间',
	-- 商品类型(S:二手，P:促销)
	COMMODITY_TYPE CHAR(1) DEFAULT 'P' NOT NULL COMMENT '商品类型(S:二手，P:促销)',
	-- 商品的价格
	COMMODITY_PRICE FLOAT(10,2) UNSIGNED COMMENT '商品的价格',
	-- 用户系统主键
	USER_ID INT NOT NULL COMMENT '用户系统主键',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) DEFAULT 'N' NOT NULL COMMENT '激活标志位',
	PRIMARY KEY (COMMODITY_ID)
) ENGINE = InnoDB COMMENT = '商品信息表' DEFAULT CHARACTER SET utf8;


-- 商品图像表
CREATE TABLE T_DA_COMMODITYIMAGE
(
	-- 商品图像系统主键
	COMMODITYIMAGE_ID INT NOT NULL AUTO_INCREMENT COMMENT '商品图像系统主键',
	-- 商品图像内容
	COMMODITYIMAGE_CONTENT BLOB NOT NULL COMMENT '商品图像内容',
	-- 创建者
	CREATED_BY VARCHAR(30) COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) COMMENT '激活标志位',
	-- 商品系统主键
	COMMODITY_ID INT NOT NULL COMMENT '商品系统主键',
	PRIMARY KEY (COMMODITYIMAGE_ID)
) ENGINE = InnoDB COMMENT = '商品图像表' DEFAULT CHARACTER SET utf8;


-- 联系方法表
CREATE TABLE T_DA_CONTACT
(
	-- 联系方法系统主键
	CONTACT_ID INT NOT NULL AUTO_INCREMENT COMMENT '联系方法系统主键',
	-- 联系方式内容
	CONTACT_CONTENT VARCHAR(30) NOT NULL COMMENT '联系方式内容',
	-- 联系方式: Q:qq, N:MSN
	CONTACT_TYPE CHAR(1) DEFAULT 'Q' NOT NULL COMMENT '联系方式: Q:qq, N:MSN',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) NOT NULL COMMENT '激活标志位',
	-- 供应商系统主键
	SUPPLIER_ID INT NOT NULL COMMENT '供应商系统主键',
	PRIMARY KEY (CONTACT_ID)
) ENGINE = InnoDB COMMENT = '联系方法表' DEFAULT CHARACTER SET utf8;


-- 国家信息表
CREATE TABLE T_DA_COUNTRY
(
	-- 国家信息的系统主键
	COUNTRY_ID INT NOT NULL AUTO_INCREMENT COMMENT '国家信息的系统主键',
	-- 国家中文名
	COUNTRY_NAME VARCHAR(30) NOT NULL COMMENT '国家中文名',
	-- 国家名字母缩写
	COUNTRY_ABBREVIATION VARCHAR(5) NOT NULL COMMENT '国家名字母缩写',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) DEFAULT 'N' NOT NULL COMMENT '激活标志位',
	PRIMARY KEY (COUNTRY_ID)
) ENGINE = InnoDB COMMENT = '国家信息表' DEFAULT CHARACTER SET utf8;


-- 访问历史表
CREATE TABLE T_DA_HISTORY
(
	-- 访问历史系统主键
	HISTORY_ID INT NOT NULL AUTO_INCREMENT COMMENT '访问历史系统主键',
	-- 访问内容类型(B:品牌,C:大类,P:产品,E:品牌产品,S:供应商)
	HISTORY_TYPE CHAR(1) NOT NULL COMMENT '访问内容类型(B:品牌,C:大类,P:产品,E:品牌产品,S:供应商)',
	-- 所对应的ID,如产品ID,供应商ID
	HISTORY_TYPEID INT NOT NULL COMMENT '所对应的ID,如产品ID,供应商ID',
	-- 访问时间
	HISTORY_ACCESSDATE DATETIME NOT NULL COMMENT '访问时间',
	PRIMARY KEY (HISTORY_ID)
) ENGINE = InnoDB COMMENT = '访问历史表' DEFAULT CHARACTER SET utf8;


-- 产品信息表
CREATE TABLE T_DA_PRODUCT
(
	-- 产品系统主键
	PRODUCT_ID INT NOT NULL AUTO_INCREMENT COMMENT '产品系统主键',
	-- 产品中文名
	PRODUCT_NAME VARCHAR(20) NOT NULL COMMENT '产品中文名',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) DEFAULT 'N' NOT NULL COMMENT '激活标志位',
	-- 产品类别名系统主键
	CATEGORY_ID INT NOT NULL COMMENT '产品类别名系统主键',
	PRIMARY KEY (PRODUCT_ID)
) ENGINE = InnoDB COMMENT = '产品信息表' DEFAULT CHARACTER SET utf8;


-- 品牌产品关系表
CREATE TABLE T_DA_PRODUCTBRAND
(
	-- 品牌产品系统主键
	PRODUCTBRAND_ID INT NOT NULL AUTO_INCREMENT COMMENT '品牌产品系统主键',
	-- 品牌系统主键
	BRAND_ID INT NOT NULL COMMENT '品牌系统主键',
	-- 产品系统主键
	PRODUCT_ID INT NOT NULL COMMENT '产品系统主键',
	-- 创建者
	CREATED_BY VARCHAR(30) COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) DEFAULT 'N' COMMENT '激活标志位',
	PRIMARY KEY (PRODUCTBRAND_ID)
) ENGINE = InnoDB COMMENT = '品牌产品关系表' DEFAULT CHARACTER SET utf8;


-- 省份信息表，记录中国每个省的基本信息。
CREATE TABLE T_DA_PROVINCE
(
	-- 省份的系统主键
	PROVINCE_ID INT NOT NULL AUTO_INCREMENT COMMENT '省份的系统主键',
	-- 省份的中文名称；如辽宁省等
	PROVINCE_NAME VARCHAR(20) NOT NULL COMMENT '省份的中文名称；如辽宁省等',
	-- 省份的字母缩写,如辽宁省为LN,均为大写
	PROVINCE_ABBREVIATION VARCHAR(3) NOT NULL COMMENT '省份的字母缩写,如辽宁省为LN,均为大写',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) DEFAULT 'N' NOT NULL COMMENT '激活标志位',
	PRIMARY KEY (PROVINCE_ID)
) ENGINE = InnoDB COMMENT = '省份信息表，记录中国每个省的基本信息。' DEFAULT CHARACTER SET utf8;


-- 角色信息表
CREATE TABLE T_DA_ROLE
(
	-- 角色系统主键
	ROLE_ID INT NOT NULL AUTO_INCREMENT COMMENT '角色系统主键',
	-- 角色名称
	ROLE_NAME VARCHAR(30) NOT NULL COMMENT '角色名称',
	-- 角色描述
	ROLE_DESCRIPTION VARCHAR(300) NOT NULL COMMENT '角色描述',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) DEFAULT 'N' NOT NULL COMMENT '激活标志位',
	PRIMARY KEY (ROLE_ID)
) ENGINE = InnoDB COMMENT = '角色信息表' DEFAULT CHARACTER SET utf8;


-- 主要用于系统主键ID生成.
CREATE TABLE T_DA_SEQUENCE
(
	-- 系统主键名
	NAME VARCHAR(30) NOT NULL COMMENT '系统主键名',
	-- 系统主键值
	NEXTID INT NOT NULL COMMENT '系统主键值',
	PRIMARY KEY (NAME)
) ENGINE = InnoDB COMMENT = '主要用于系统主键ID生成.' DEFAULT CHARACTER SET utf8;


-- 代理商信息，没有完成.
CREATE TABLE T_DA_SUPPLIER
(
	-- 供应商系统主键
	SUPPLIER_ID INT NOT NULL AUTO_INCREMENT COMMENT '供应商系统主键',
	-- 供应商名称
	SUPPLIER_NAME VARCHAR(20) NOT NULL COMMENT '供应商名称',
	-- 联系人
	SUPPLIER_CONTACTNAME VARCHAR(30) NOT NULL COMMENT '联系人',
	-- 邮政编码
	SUPPLIER_ZIP VARCHAR(6) NOT NULL COMMENT '邮政编码',
	-- 图片
	SUPPLIER_IMAGE BLOB NOT NULL COMMENT '图片',
	-- 简介
	SUPPLIER_DESCRIPTION VARCHAR(3000) NOT NULL COMMENT '简介',
	-- 传真
	SUPPLIER_FAX VARCHAR(30) NOT NULL COMMENT '传真',
	-- 手机
	SUPPLIER_MOBILE VARCHAR(30) NOT NULL COMMENT '手机',
	-- 联系电话
	SUPPLIER_TELEPHONE VARCHAR(30) NOT NULL COMMENT '联系电话',
	-- 联系地址
	SUPPLIER_ADDRESS VARCHAR(30) NOT NULL COMMENT '联系地址',
	-- 实名认证
	SUPPLIER_CERTIFY BLOB COMMENT '实名认证',
	-- 资质认证
	SUPPLIER_QUALIFY BLOB COMMENT '资质认证',
	-- 城市系统主键
	CITY_ID INT NOT NULL COMMENT '城市系统主键',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) NOT NULL COMMENT '激活标志位',
	-- 用户系统主键
	USER_ID INT NOT NULL COMMENT '用户系统主键',
	PRIMARY KEY (SUPPLIER_ID)
) ENGINE = InnoDB COMMENT = '代理商信息，没有完成.' DEFAULT CHARACTER SET utf8;


-- 供应商与品牌产品关系表
CREATE TABLE T_DA_SUPPLIERPRODUCT
(
	-- 供应商系统主键
	SUPPLIER_ID INT NOT NULL COMMENT '供应商系统主键',
	-- 品牌产品系统主键
	PRODUCTBRAND_ID INT NOT NULL COMMENT '品牌产品系统主键',
	PRIMARY KEY (SUPPLIER_ID, PRODUCTBRAND_ID)
) ENGINE = InnoDB COMMENT = '供应商与品牌产品关系表' DEFAULT CHARACTER SET utf8;


-- 用户信息表
CREATE TABLE T_DA_USER
(
	-- 用户系统主键
	USER_ID INT NOT NULL AUTO_INCREMENT COMMENT '用户系统主键',
	-- 用户名
	USER_NAME VARCHAR(30) NOT NULL COMMENT '用户名',
	-- 电子邮件
	USER_EMAIL VARCHAR(100) NOT NULL COMMENT '电子邮件',
	-- 用户密码
	USER_PASSWORD VARCHAR(30) NOT NULL COMMENT '用户密码',
	-- 上次登录时间
	LASTLOGINTIME DATETIME NOT NULL COMMENT '上次登录时间',
	-- 注册时间
	REGISTERTIME DATETIME NOT NULL COMMENT '注册时间',
	-- 登录次数
	LOGONSUM INT NOT NULL COMMENT '登录次数',
	-- 创建者
	CREATED_BY VARCHAR(30) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATED_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 最后更新者
	LASTUPDATED_BY VARCHAR(30) NOT NULL COMMENT '最后更新者',
	-- 最后更新时间
	LASTUPDATED_DATE DATETIME NOT NULL COMMENT '最后更新时间',
	-- 激活标志位
	ACTIVE_FLAG CHAR(1) DEFAULT 'N' NOT NULL COMMENT '激活标志位',
	PRIMARY KEY (USER_ID)
) ENGINE = InnoDB COMMENT = '用户信息表' DEFAULT CHARACTER SET utf8;


-- 用户和角色关系表
CREATE TABLE T_DA_USERROLE
(
	-- 用户系统主键
	USER_ID INT NOT NULL COMMENT '用户系统主键',
	-- 角色系统主键
	ROLE_ID INT NOT NULL COMMENT '角色系统主键'
) ENGINE = InnoDB COMMENT = '用户和角色关系表' DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */

ALTER TABLE T_DA_PRODUCTBRAND
	ADD FOREIGN KEY (BRAND_ID)
	REFERENCES T_DA_BRAND (BRAND_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_PRODUCT
	ADD FOREIGN KEY (CATEGORY_ID)
	REFERENCES T_DA_CATEGORY (CATEGORY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_SUPPLIER
	ADD FOREIGN KEY (CITY_ID)
	REFERENCES T_DA_CITY (CITY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_COMMODITYIMAGE
	ADD FOREIGN KEY (COMMODITY_ID)
	REFERENCES T_DA_COMMODITY (COMMODITY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_BRAND
	ADD FOREIGN KEY (COUNTRY_ID)
	REFERENCES T_DA_COUNTRY (COUNTRY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_PRODUCTBRAND
	ADD FOREIGN KEY (PRODUCT_ID)
	REFERENCES T_DA_PRODUCT (PRODUCT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_SUPPLIERPRODUCT
	ADD FOREIGN KEY (PRODUCTBRAND_ID)
	REFERENCES T_DA_PRODUCTBRAND (PRODUCTBRAND_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_CITY
	ADD FOREIGN KEY (PROVINCE_ID)
	REFERENCES T_DA_PROVINCE (PROVINCE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_USERROLE
	ADD FOREIGN KEY (ROLE_ID)
	REFERENCES T_DA_ROLE (ROLE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_CONTACT
	ADD FOREIGN KEY (SUPPLIER_ID)
	REFERENCES T_DA_SUPPLIER (SUPPLIER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_SUPPLIERPRODUCT
	ADD FOREIGN KEY (SUPPLIER_ID)
	REFERENCES T_DA_SUPPLIER (SUPPLIER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_COMMODITY
	ADD FOREIGN KEY (USER_ID)
	REFERENCES T_DA_USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_SUPPLIER
	ADD FOREIGN KEY (USER_ID)
	REFERENCES T_DA_USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE T_DA_USERROLE
	ADD FOREIGN KEY (USER_ID)
	REFERENCES T_DA_USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Create Indexes */

CREATE INDEX IDX_DA_PROVINCE_ID ON T_DA_PROVINCE (PROVINCE_ID ASC);



