
/* Drop Indexes */

DROP INDEX IDX_DA_PROVINCE_ID ON T_DA_PROVINCE;



/* Drop Tables */

DROP TABLE T_DA_SUPPLIERPRODUCT;
DROP TABLE T_DA_PRODUCTBRAND;
DROP TABLE T_DA_BRAND;
DROP TABLE T_DA_PRODUCT;
DROP TABLE T_DA_CATEGORY;
DROP TABLE T_DA_CONTACT;
DROP TABLE T_DA_SUPPLIER;
DROP TABLE T_DA_CITY;
DROP TABLE T_DA_COMMODITYIMAGE;
DROP TABLE T_DA_COMMODITY;
DROP TABLE T_DA_COUNTRY;
DROP TABLE T_DA_HISTORY;
DROP TABLE T_DA_PROVINCE;
DROP TABLE T_DA_USERROLE;
DROP TABLE T_DA_ROLE;
DROP TABLE T_DA_USER;



