DELIMITER $$

CREATE DEFINER=`digiagent`@`%` PROCEDURE `GET_SORTABLE_CHILD`(IN IN_ID INT,OUT OUT_IDS VARCHAR(10000))
BEGIN
DECLARE V_STOP BOOLEAN DEFAULT FALSE;
DECLARE V_ID INT;
DECLARE V_SUB_IDS VARCHAR(10000);
DECLARE V_IDS VARCHAR(10000);

DECLARE CUR1 CURSOR FOR SELECT SORTABLE_ID FROM T_DA_SORTABLE WHERE PARENT_ID = IN_ID;
DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET V_STOP = TRUE;

SET @@max_sp_recursion_depth = 10;

OPEN CUR1;

LAB1:WHILE NOT V_STOP DO
    FETCH CUR1 INTO V_ID;
    IF V_STOP THEN
      LEAVE LAB1;
    END IF;
    CALL GET_SORTABLE_CHILD(V_ID,V_SUB_IDS);
    SET V_IDS = CONCAT_WS(',',V_IDS,V_ID,V_SUB_IDS);
END WHILE LAB1;
SET OUT_IDS = V_IDS;
END


----------------------
