DELIMITER $$

CREATE DEFINER=`digiagent`@`%` PROCEDURE `GET_SORTABLE_CHILD`(IN IN_ID INT,OUT OUT_IDS VARCHAR(10000))
BEGIN
DECLARE V_STOP BOOLEAN DEFAULT FALSE;
DECLARE V_ID INT;
DECLARE V_SUB_IDS VARCHAR(10000);
DECLARE V_IDS VARCHAR(10000);

DECLARE CUR1 CURSOR FOR SELECT SORTABLE_ID FROM T_DA_SORTABLE WHERE PARENT_ID = IN_ID;
DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET V_STOP = TRUE;

SET @@max_sp_recursion_depth = 10;

OPEN CUR1;

LAB1:WHILE NOT V_STOP DO
    FETCH CUR1 INTO V_ID;
    IF V_STOP THEN
      LEAVE LAB1;
    END IF;
    CALL GET_SORTABLE_CHILD(V_ID,V_SUB_IDS);
    SET V_IDS = CONCAT_WS(',',V_IDS,V_ID,V_SUB_IDS);
END WHILE LAB1;
SET OUT_IDS = V_IDS;
END


----------------------
-- 排序表
CREATE TABLE T_DA_SORTABLE
(
	-- 排序表系统的主键
	SORTABLE_ID INT NOT NULL COMMENT '排序表系统的主键',
	-- 需要排序的表的系统工主键，主要来源于category,brand,product
	SORTABLE_KEY INT NOT NULL COMMENT '需要排序的表的系统工主键，主要来源于category,brand,product',
	-- 所对应的排序位
	SORTABLE_ORDER INT DEFAULT 0 NOT NULL COMMENT '所对应的排序位',
	-- 所对应的排序类型, C为category, B为Brand, P为Product
	SORTABLE_TYPE CHAR(1) NOT NULL COMMENT '所对应的排序类型, C为category, B为Brand, P为Product',
	-- 排序表系统的主键
	PARENT_ID INT COMMENT '排序表系统的主键',
	PRIMARY KEY (SORTABLE_ID),
	KEY `FK_PARENT` (`PARENT_ID`)
) ENGINE = InnoDB COMMENT = '排序表' DEFAULT CHARACTER SET utf8;


ALTER TABLE T_DA_SORTABLE
	ADD CONSTRAINT FOREIGN KEY (PARENT_ID)
	REFERENCES T_DA_SORTABLE (SORTABLE_ID)
	ON UPDATE RESTRICT
	ON DELETE CASCADE
;