package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.Product;
import net.cominfo.digiagent.persistence.domain.ProductCriteria;

public interface ProductDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Oct 12 21:05:52 CST 2010
	 */
	int countByExample(ProductCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Oct 12 21:05:52 CST 2010
	 */
	int deleteByExample(ProductCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Oct 12 21:05:52 CST 2010
	 */
	int deleteByPrimaryKey(Integer productId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Oct 12 21:05:52 CST 2010
	 */
	void insert(Product record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Oct 12 21:05:52 CST 2010
	 */
	void insertSelective(Product record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Oct 12 21:05:52 CST 2010
	 */
	List<Product> selectByExample(ProductCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Oct 12 21:05:52 CST 2010
	 */
	Product selectByPrimaryKey(Integer productId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Oct 12 21:05:52 CST 2010
	 */
	int updateByExampleSelective(Product record, ProductCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Oct 12 21:05:52 CST 2010
	 */
	int updateByExample(Product record, ProductCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Oct 12 21:05:52 CST 2010
	 */
	int updateByPrimaryKeySelective(Product record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Oct 12 21:05:52 CST 2010
	 */
	int updateByPrimaryKey(Product record);
}