package net.cominfo.digiagent.persistence.domain;

import java.io.Serializable;
import java.util.Date;

public class Contact implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_contact.CONTACT_ID
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	private Integer contactId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_contact.CONTACT_CONTENT
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	private String contactContent;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_contact.CONTACT_TYPE
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	private String contactType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_contact.CREATED_BY
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	private String createdBy;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_contact.CREATED_DATE
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	private Date createdDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_contact.LASTUPDATED_BY
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	private String lastupdatedBy;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_contact.LASTUPDATED_DATE
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	private Date lastupdatedDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_contact.ACTIVE_FLAG
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	private String activeFlag;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_contact.SUPPLIER_ID
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	private Integer supplierId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_da_contact
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_contact.CONTACT_ID
	 * @return  the value of t_da_contact.CONTACT_ID
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public Integer getContactId() {
		return contactId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_contact.CONTACT_ID
	 * @param contactId  the value for t_da_contact.CONTACT_ID
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_contact.CONTACT_CONTENT
	 * @return  the value of t_da_contact.CONTACT_CONTENT
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public String getContactContent() {
		return contactContent;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_contact.CONTACT_CONTENT
	 * @param contactContent  the value for t_da_contact.CONTACT_CONTENT
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public void setContactContent(String contactContent) {
		this.contactContent = contactContent;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_contact.CONTACT_TYPE
	 * @return  the value of t_da_contact.CONTACT_TYPE
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public String getContactType() {
		return contactType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_contact.CONTACT_TYPE
	 * @param contactType  the value for t_da_contact.CONTACT_TYPE
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public void setContactType(String contactType) {
		this.contactType = contactType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_contact.CREATED_BY
	 * @return  the value of t_da_contact.CREATED_BY
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_contact.CREATED_BY
	 * @param createdBy  the value for t_da_contact.CREATED_BY
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_contact.CREATED_DATE
	 * @return  the value of t_da_contact.CREATED_DATE
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_contact.CREATED_DATE
	 * @param createdDate  the value for t_da_contact.CREATED_DATE
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_contact.LASTUPDATED_BY
	 * @return  the value of t_da_contact.LASTUPDATED_BY
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public String getLastupdatedBy() {
		return lastupdatedBy;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_contact.LASTUPDATED_BY
	 * @param lastupdatedBy  the value for t_da_contact.LASTUPDATED_BY
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public void setLastupdatedBy(String lastupdatedBy) {
		this.lastupdatedBy = lastupdatedBy;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_contact.LASTUPDATED_DATE
	 * @return  the value of t_da_contact.LASTUPDATED_DATE
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public Date getLastupdatedDate() {
		return lastupdatedDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_contact.LASTUPDATED_DATE
	 * @param lastupdatedDate  the value for t_da_contact.LASTUPDATED_DATE
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public void setLastupdatedDate(Date lastupdatedDate) {
		this.lastupdatedDate = lastupdatedDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_contact.ACTIVE_FLAG
	 * @return  the value of t_da_contact.ACTIVE_FLAG
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public String getActiveFlag() {
		return activeFlag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_contact.ACTIVE_FLAG
	 * @param activeFlag  the value for t_da_contact.ACTIVE_FLAG
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_contact.SUPPLIER_ID
	 * @return  the value of t_da_contact.SUPPLIER_ID
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public Integer getSupplierId() {
		return supplierId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_contact.SUPPLIER_ID
	 * @param supplierId  the value for t_da_contact.SUPPLIER_ID
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_contact
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof Contact)) {
			return false;
		}
		Contact other = (Contact) that;
		return this.getContactId() == null ? other == null : this
				.getContactId().equals(other.getContactId())
				&& this.getContactContent() == null ? other == null : this
				.getContactContent().equals(other.getContactContent())
				&& this.getContactType() == null ? other == null : this
				.getContactType().equals(other.getContactType())
				&& this.getCreatedBy() == null ? other == null : this
				.getCreatedBy().equals(other.getCreatedBy())
				&& this.getCreatedDate() == null ? other == null : this
				.getCreatedDate().equals(other.getCreatedDate())
				&& this.getLastupdatedBy() == null ? other == null : this
				.getLastupdatedBy().equals(other.getLastupdatedBy())
				&& this.getLastupdatedDate() == null ? other == null : this
				.getLastupdatedDate().equals(other.getLastupdatedDate())
				&& this.getActiveFlag() == null ? other == null : this
				.getActiveFlag().equals(other.getActiveFlag())
				&& this.getSupplierId() == null ? other == null : this
				.getSupplierId().equals(other.getSupplierId());
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_contact
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	@Override
	public int hashCode() {
		int hash = 23;
		if (getContactId() != null) {
			hash *= getContactId().hashCode();
		}
		if (getContactContent() != null) {
			hash *= getContactContent().hashCode();
		}
		if (getContactType() != null) {
			hash *= getContactType().hashCode();
		}
		if (getCreatedBy() != null) {
			hash *= getCreatedBy().hashCode();
		}
		if (getCreatedDate() != null) {
			hash *= getCreatedDate().hashCode();
		}
		if (getLastupdatedBy() != null) {
			hash *= getLastupdatedBy().hashCode();
		}
		if (getLastupdatedDate() != null) {
			hash *= getLastupdatedDate().hashCode();
		}
		if (getActiveFlag() != null) {
			hash *= getActiveFlag().hashCode();
		}
		if (getSupplierId() != null) {
			hash *= getSupplierId().hashCode();
		}
		return hash;
	}
}