package net.cominfo.digiagent.persistence.domain;

import java.io.Serializable;
import java.util.Date;

public class ProductBrand implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_productbrand.PRODUCTBRAND_ID
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	private Integer productbrandId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_productbrand.BRAND_ID
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	private Integer brandId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_productbrand.PRODUCT_ID
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	private Integer productId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_productbrand.CREATED_BY
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	private String createdBy;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_productbrand.CREATED_DATE
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	private Date createdDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_productbrand.LASTUPDATED_BY
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	private String lastupdatedBy;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_productbrand.LASTUPDATED_DATE
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	private Date lastupdatedDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_productbrand.ACTIVE_FLAG
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	private String activeFlag;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_da_productbrand
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_productbrand.PRODUCTBRAND_ID
	 * @return  the value of t_da_productbrand.PRODUCTBRAND_ID
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public Integer getProductbrandId() {
		return productbrandId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_productbrand.PRODUCTBRAND_ID
	 * @param productbrandId  the value for t_da_productbrand.PRODUCTBRAND_ID
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public void setProductbrandId(Integer productbrandId) {
		this.productbrandId = productbrandId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_productbrand.BRAND_ID
	 * @return  the value of t_da_productbrand.BRAND_ID
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public Integer getBrandId() {
		return brandId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_productbrand.BRAND_ID
	 * @param brandId  the value for t_da_productbrand.BRAND_ID
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_productbrand.PRODUCT_ID
	 * @return  the value of t_da_productbrand.PRODUCT_ID
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_productbrand.PRODUCT_ID
	 * @param productId  the value for t_da_productbrand.PRODUCT_ID
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_productbrand.CREATED_BY
	 * @return  the value of t_da_productbrand.CREATED_BY
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_productbrand.CREATED_BY
	 * @param createdBy  the value for t_da_productbrand.CREATED_BY
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_productbrand.CREATED_DATE
	 * @return  the value of t_da_productbrand.CREATED_DATE
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_productbrand.CREATED_DATE
	 * @param createdDate  the value for t_da_productbrand.CREATED_DATE
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_productbrand.LASTUPDATED_BY
	 * @return  the value of t_da_productbrand.LASTUPDATED_BY
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public String getLastupdatedBy() {
		return lastupdatedBy;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_productbrand.LASTUPDATED_BY
	 * @param lastupdatedBy  the value for t_da_productbrand.LASTUPDATED_BY
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public void setLastupdatedBy(String lastupdatedBy) {
		this.lastupdatedBy = lastupdatedBy;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_productbrand.LASTUPDATED_DATE
	 * @return  the value of t_da_productbrand.LASTUPDATED_DATE
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public Date getLastupdatedDate() {
		return lastupdatedDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_productbrand.LASTUPDATED_DATE
	 * @param lastupdatedDate  the value for t_da_productbrand.LASTUPDATED_DATE
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public void setLastupdatedDate(Date lastupdatedDate) {
		this.lastupdatedDate = lastupdatedDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_productbrand.ACTIVE_FLAG
	 * @return  the value of t_da_productbrand.ACTIVE_FLAG
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public String getActiveFlag() {
		return activeFlag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_productbrand.ACTIVE_FLAG
	 * @param activeFlag  the value for t_da_productbrand.ACTIVE_FLAG
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_productbrand
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof ProductBrand)) {
			return false;
		}
		ProductBrand other = (ProductBrand) that;
		return this.getProductbrandId() == null ? other == null : this
				.getProductbrandId().equals(other.getProductbrandId())
				&& this.getBrandId() == null ? other == null : this
				.getBrandId().equals(other.getBrandId())
				&& this.getProductId() == null ? other == null : this
				.getProductId().equals(other.getProductId())
				&& this.getCreatedBy() == null ? other == null : this
				.getCreatedBy().equals(other.getCreatedBy())
				&& this.getCreatedDate() == null ? other == null : this
				.getCreatedDate().equals(other.getCreatedDate())
				&& this.getLastupdatedBy() == null ? other == null : this
				.getLastupdatedBy().equals(other.getLastupdatedBy())
				&& this.getLastupdatedDate() == null ? other == null : this
				.getLastupdatedDate().equals(other.getLastupdatedDate())
				&& this.getActiveFlag() == null ? other == null : this
				.getActiveFlag().equals(other.getActiveFlag());
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_productbrand
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	@Override
	public int hashCode() {
		int hash = 23;
		if (getProductbrandId() != null) {
			hash *= getProductbrandId().hashCode();
		}
		if (getBrandId() != null) {
			hash *= getBrandId().hashCode();
		}
		if (getProductId() != null) {
			hash *= getProductId().hashCode();
		}
		if (getCreatedBy() != null) {
			hash *= getCreatedBy().hashCode();
		}
		if (getCreatedDate() != null) {
			hash *= getCreatedDate().hashCode();
		}
		if (getLastupdatedBy() != null) {
			hash *= getLastupdatedBy().hashCode();
		}
		if (getLastupdatedDate() != null) {
			hash *= getLastupdatedDate().hashCode();
		}
		if (getActiveFlag() != null) {
			hash *= getActiveFlag().hashCode();
		}
		return hash;
	}
}