package net.cominfo.digiagent.persistence.domain;

import java.io.Serializable;

public class Sortable implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_da_sortable.SORTABLE_ID
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    private Integer sortableId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_da_sortable.SORTABLE_KEY
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    private Integer sortableKey;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_da_sortable.SORTABLE_ORDER
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    private Integer sortableOrder;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_da_sortable.SORTABLE_TYPE
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    private String sortableType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_da_sortable.PARENT_ID
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    private Integer parentId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table t_da_sortable
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_da_sortable.SORTABLE_ID
     *
     * @return the value of t_da_sortable.SORTABLE_ID
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    public Integer getSortableId() {
        return sortableId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_da_sortable.SORTABLE_ID
     *
     * @param sortableId the value for t_da_sortable.SORTABLE_ID
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    public void setSortableId(Integer sortableId) {
        this.sortableId = sortableId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_da_sortable.SORTABLE_KEY
     *
     * @return the value of t_da_sortable.SORTABLE_KEY
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    public Integer getSortableKey() {
        return sortableKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_da_sortable.SORTABLE_KEY
     *
     * @param sortableKey the value for t_da_sortable.SORTABLE_KEY
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    public void setSortableKey(Integer sortableKey) {
        this.sortableKey = sortableKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_da_sortable.SORTABLE_ORDER
     *
     * @return the value of t_da_sortable.SORTABLE_ORDER
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    public Integer getSortableOrder() {
        return sortableOrder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_da_sortable.SORTABLE_ORDER
     *
     * @param sortableOrder the value for t_da_sortable.SORTABLE_ORDER
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    public void setSortableOrder(Integer sortableOrder) {
        this.sortableOrder = sortableOrder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_da_sortable.SORTABLE_TYPE
     *
     * @return the value of t_da_sortable.SORTABLE_TYPE
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    public String getSortableType() {
        return sortableType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_da_sortable.SORTABLE_TYPE
     *
     * @param sortableType the value for t_da_sortable.SORTABLE_TYPE
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    public void setSortableType(String sortableType) {
        this.sortableType = sortableType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_da_sortable.PARENT_ID
     *
     * @return the value of t_da_sortable.PARENT_ID
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_da_sortable.PARENT_ID
     *
     * @param parentId the value for t_da_sortable.PARENT_ID
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_sortable
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof Sortable)) {
            return false;
        }
        Sortable other = (Sortable) that;
        return this.getSortableId() == null ? other == null : this.getSortableId().equals(other.getSortableId())
            && this.getSortableKey() == null ? other == null : this.getSortableKey().equals(other.getSortableKey())
            && this.getSortableOrder() == null ? other == null : this.getSortableOrder().equals(other.getSortableOrder())
            && this.getSortableType() == null ? other == null : this.getSortableType().equals(other.getSortableType())
            && this.getParentId() == null ? other == null : this.getParentId().equals(other.getParentId());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_sortable
     *
     * @ibatorgenerated Thu Dec 09 22:07:35 CST 2010
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getSortableId() != null) {
            hash *= getSortableId().hashCode();
        }
        if (getSortableKey() != null) {
            hash *= getSortableKey().hashCode();
        }
        if (getSortableOrder() != null) {
            hash *= getSortableOrder().hashCode();
        }
        if (getSortableType() != null) {
            hash *= getSortableType().hashCode();
        }
        if (getParentId() != null) {
            hash *= getParentId().hashCode();
        }
        return hash;
    }
}