package net.cominfo.digiagent.persistence.domain;

import java.io.Serializable;
import java.util.Date;

public class SupplierProduct extends SupplierProductKey implements Serializable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_supplierproduct.CREATE_DATE
	 * @ibatorgenerated  Wed Oct 06 13:56:41 CST 2010
	 */
	private Date createDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_supplierproduct.START_DATE
	 * @ibatorgenerated  Wed Oct 06 13:56:41 CST 2010
	 */
	private Date startDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_da_supplierproduct.END_DATE
	 * @ibatorgenerated  Wed Oct 06 13:56:41 CST 2010
	 */
	private Date endDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_da_supplierproduct
	 * @ibatorgenerated  Wed Oct 06 13:56:41 CST 2010
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_supplierproduct.CREATE_DATE
	 * @return  the value of t_da_supplierproduct.CREATE_DATE
	 * @ibatorgenerated  Wed Oct 06 13:56:41 CST 2010
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_supplierproduct.CREATE_DATE
	 * @param createDate  the value for t_da_supplierproduct.CREATE_DATE
	 * @ibatorgenerated  Wed Oct 06 13:56:41 CST 2010
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_supplierproduct.START_DATE
	 * @return  the value of t_da_supplierproduct.START_DATE
	 * @ibatorgenerated  Wed Oct 06 13:56:41 CST 2010
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_supplierproduct.START_DATE
	 * @param startDate  the value for t_da_supplierproduct.START_DATE
	 * @ibatorgenerated  Wed Oct 06 13:56:41 CST 2010
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_da_supplierproduct.END_DATE
	 * @return  the value of t_da_supplierproduct.END_DATE
	 * @ibatorgenerated  Wed Oct 06 13:56:41 CST 2010
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_da_supplierproduct.END_DATE
	 * @param endDate  the value for t_da_supplierproduct.END_DATE
	 * @ibatorgenerated  Wed Oct 06 13:56:41 CST 2010
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_supplierproduct
	 * @ibatorgenerated  Wed Oct 06 13:56:41 CST 2010
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof SupplierProduct)) {
			return false;
		}
		SupplierProduct other = (SupplierProduct) that;
		return this.getProductbrandId() == null ? other == null : this
				.getProductbrandId().equals(other.getProductbrandId())
				&& this.getSupplierId() == null ? other == null : this
				.getSupplierId().equals(other.getSupplierId())
				&& this.getCreateDate() == null ? other == null : this
				.getCreateDate().equals(other.getCreateDate())
				&& this.getStartDate() == null ? other == null : this
				.getStartDate().equals(other.getStartDate())
				&& this.getEndDate() == null ? other == null : this
				.getEndDate().equals(other.getEndDate());
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_supplierproduct
	 * @ibatorgenerated  Wed Oct 06 13:56:41 CST 2010
	 */
	@Override
	public int hashCode() {
		int hash = 23;
		if (getProductbrandId() != null) {
			hash *= getProductbrandId().hashCode();
		}
		if (getSupplierId() != null) {
			hash *= getSupplierId().hashCode();
		}
		if (getCreateDate() != null) {
			hash *= getCreateDate().hashCode();
		}
		if (getStartDate() != null) {
			hash *= getStartDate().hashCode();
		}
		if (getEndDate() != null) {
			hash *= getEndDate().hashCode();
		}
		return hash;
	}
}