package name.huangzhoujin.registration.persistence.domain;

import java.io.Serializable;

public class Location implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reg_location.LOCATION_ID
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    private Integer locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reg_location.LOCATION_NAME
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    private String locationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_reg_location
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reg_location.LOCATION_ID
     *
     * @return the value of t_reg_location.LOCATION_ID
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reg_location.LOCATION_ID
     *
     * @param locationId the value for t_reg_location.LOCATION_ID
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reg_location.LOCATION_NAME
     *
     * @return the value of t_reg_location.LOCATION_NAME
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    public String getLocationName() {
        return locationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reg_location.LOCATION_NAME
     *
     * @param locationName the value for t_reg_location.LOCATION_NAME
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    public void setLocationName(String locationName) {
        this.locationName = locationName == null ? null : locationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_location
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Location other = (Location) that;
        return (this.getLocationId() == null ? other.getLocationId() == null : this.getLocationId().equals(other.getLocationId()))
            && (this.getLocationName() == null ? other.getLocationName() == null : this.getLocationName().equals(other.getLocationName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_location
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLocationId() == null) ? 0 : getLocationId().hashCode());
        result = prime * result + ((getLocationName() == null) ? 0 : getLocationName().hashCode());
        return result;
    }
}