package name.huangzhoujin.registration.persistence.domain;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reg_user.USER_ID
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reg_user.USERNAME
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reg_user.PASSWORD
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reg_user.EMAIL
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reg_user.ROLE_FLAG
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    private String roleFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reg_user.ACTIVE
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_reg_user
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reg_user.USER_ID
     *
     * @return the value of t_reg_user.USER_ID
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reg_user.USER_ID
     *
     * @param userId the value for t_reg_user.USER_ID
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reg_user.USERNAME
     *
     * @return the value of t_reg_user.USERNAME
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reg_user.USERNAME
     *
     * @param username the value for t_reg_user.USERNAME
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reg_user.PASSWORD
     *
     * @return the value of t_reg_user.PASSWORD
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reg_user.PASSWORD
     *
     * @param password the value for t_reg_user.PASSWORD
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reg_user.EMAIL
     *
     * @return the value of t_reg_user.EMAIL
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reg_user.EMAIL
     *
     * @param email the value for t_reg_user.EMAIL
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reg_user.ROLE_FLAG
     *
     * @return the value of t_reg_user.ROLE_FLAG
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    public String getRoleFlag() {
        return roleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reg_user.ROLE_FLAG
     *
     * @param roleFlag the value for t_reg_user.ROLE_FLAG
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    public void setRoleFlag(String roleFlag) {
        this.roleFlag = roleFlag == null ? null : roleFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reg_user.ACTIVE
     *
     * @return the value of t_reg_user.ACTIVE
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reg_user.ACTIVE
     *
     * @param active the value for t_reg_user.ACTIVE
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_user
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getRoleFlag() == null ? other.getRoleFlag() == null : this.getRoleFlag().equals(other.getRoleFlag()))
            && (this.getActive() == null ? other.getActive() == null : this.getActive().equals(other.getActive()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_user
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getRoleFlag() == null) ? 0 : getRoleFlag().hashCode());
        result = prime * result + ((getActive() == null) ? 0 : getActive().hashCode());
        return result;
    }
}