package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.Advertise;
import net.cominfo.digiagent.persistence.domain.AdvertiseCriteria;

public interface AdvertiseDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    int countByExample(AdvertiseCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    int deleteByExample(AdvertiseCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    int deleteByPrimaryKey(Integer advertiseId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    void insert(Advertise record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    void insertSelective(Advertise record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    List<Advertise> selectByExample(AdvertiseCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    Advertise selectByPrimaryKey(Integer advertiseId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    int updateByExampleSelective(Advertise record, AdvertiseCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    int updateByExample(Advertise record, AdvertiseCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    int updateByPrimaryKeySelective(Advertise record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    int updateByPrimaryKey(Advertise record);
}