package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.Advertise;
import net.cominfo.digiagent.persistence.domain.AdvertiseCriteria;

public class AdvertiseDAOImpl extends BaseDao implements AdvertiseDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    public AdvertiseDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    public int countByExample(AdvertiseCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_da_advertise.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    public int deleteByExample(AdvertiseCriteria example) {
        int rows = getSqlMapClientTemplate().delete("t_da_advertise.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    public int deleteByPrimaryKey(Integer advertiseId) {
        Advertise key = new Advertise();
        key.setAdvertiseId(advertiseId);
        int rows = getSqlMapClientTemplate().delete("t_da_advertise.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    public void insert(Advertise record) {
        getSqlMapClientTemplate().insert("t_da_advertise.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    public void insertSelective(Advertise record) {
        getSqlMapClientTemplate().insert("t_da_advertise.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    @SuppressWarnings("unchecked")
    public List<Advertise> selectByExample(AdvertiseCriteria example) {
        List<Advertise> list = getSqlMapClientTemplate().queryForList("t_da_advertise.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    public Advertise selectByPrimaryKey(Integer advertiseId) {
        Advertise key = new Advertise();
        key.setAdvertiseId(advertiseId);
        Advertise record = (Advertise) getSqlMapClientTemplate().queryForObject("t_da_advertise.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    public int updateByExampleSelective(Advertise record, AdvertiseCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_da_advertise.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    public int updateByExample(Advertise record, AdvertiseCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_da_advertise.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    public int updateByPrimaryKeySelective(Advertise record) {
        int rows = getSqlMapClientTemplate().update("t_da_advertise.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    public int updateByPrimaryKey(Advertise record) {
        int rows = getSqlMapClientTemplate().update("t_da_advertise.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_da_advertise
     *
     * @ibatorgenerated Sun Apr 10 20:46:03 CST 2011
     */
    private static class UpdateByExampleParms extends AdvertiseCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, AdvertiseCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}