package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.Brand;
import net.cominfo.digiagent.persistence.domain.BrandCriteria;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BrandDAOImpl extends SqlMapClientDaoSupport implements BrandDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Wed Oct 06 10:54:15 CST 2010
	 */
	public BrandDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Wed Oct 06 10:54:15 CST 2010
	 */
	public int countByExample(BrandCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_da_brand.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Wed Oct 06 10:54:15 CST 2010
	 */
	public int deleteByExample(BrandCriteria example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_da_brand.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Wed Oct 06 10:54:15 CST 2010
	 */
	public int deleteByPrimaryKey(Integer brandId) {
		Brand key = new Brand();
		key.setBrandId(brandId);
		int rows = getSqlMapClientTemplate().delete(
				"t_da_brand.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Wed Oct 06 10:54:15 CST 2010
	 */
	public void insert(Brand record) {
		getSqlMapClientTemplate().insert("t_da_brand.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Wed Oct 06 10:54:15 CST 2010
	 */
	public void insertSelective(Brand record) {
		getSqlMapClientTemplate().insert(
				"t_da_brand.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Wed Oct 06 10:54:15 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<Brand> selectByExample(BrandCriteria example) {
		List<Brand> list = getSqlMapClientTemplate().queryForList(
				"t_da_brand.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Wed Oct 06 10:54:15 CST 2010
	 */
	public Brand selectByPrimaryKey(Integer brandId) {
		Brand key = new Brand();
		key.setBrandId(brandId);
		Brand record = (Brand) getSqlMapClientTemplate().queryForObject(
				"t_da_brand.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Wed Oct 06 10:54:15 CST 2010
	 */
	public int updateByExampleSelective(Brand record, BrandCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_da_brand.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Wed Oct 06 10:54:15 CST 2010
	 */
	public int updateByExample(Brand record, BrandCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_da_brand.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Wed Oct 06 10:54:15 CST 2010
	 */
	public int updateByPrimaryKeySelective(Brand record) {
		int rows = getSqlMapClientTemplate().update(
				"t_da_brand.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Wed Oct 06 10:54:15 CST 2010
	 */
	public int updateByPrimaryKey(Brand record) {
		int rows = getSqlMapClientTemplate().update(
				"t_da_brand.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_da_brand
	 * @ibatorgenerated  Wed Oct 06 10:54:15 CST 2010
	 */
	private static class UpdateByExampleParms extends BrandCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, BrandCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}