package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.Brand;
import net.cominfo.digiagent.persistence.domain.BrandCriteria;

public interface BrandDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int countByExample(BrandCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int deleteByExample(BrandCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int deleteByPrimaryKey(Integer brandId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	void insert(Brand record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	void insertSelective(Brand record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	List<Brand> selectByExample(BrandCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	Brand selectByPrimaryKey(Integer brandId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByExampleSelective(Brand record, BrandCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByExample(Brand record, BrandCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByPrimaryKeySelective(Brand record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_brand
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByPrimaryKey(Brand record);
}