package net.cominfo.digiagent.persistence.sqlmapdao;

import java.sql.SQLException;
import java.util.List;
import net.cominfo.digiagent.persistence.domain.Category;
import net.cominfo.digiagent.persistence.domain.CategoryCriteria;

public interface CategoryDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	int countByExample(CategoryCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	int deleteByExample(CategoryCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	int deleteByPrimaryKey(Integer categoryId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	void insert(Category record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	void insertSelective(Category record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	List<Category> selectByExample(CategoryCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	Category selectByPrimaryKey(Integer categoryId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	int updateByExampleSelective(Category record, CategoryCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	int updateByExample(Category record, CategoryCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	int updateByPrimaryKeySelective(Category record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	int updateByPrimaryKey(Category record);
	
	// FIXME expend start
	/**
	 * Pagination Query List
	 */
	List<Category> queryListByExample(CategoryCriteria example, PaginationContext paginationContext);
	// expend end
}