package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.Category;
import net.cominfo.digiagent.persistence.domain.CategoryCriteria;

public interface CategoryDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int countByExample(CategoryCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int deleteByExample(CategoryCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int deleteByPrimaryKey(Integer categoryId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	void insert(Category record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	void insertSelective(Category record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	List<Category> selectByExample(CategoryCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	Category selectByPrimaryKey(Integer categoryId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByExampleSelective(Category record, CategoryCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByExample(Category record, CategoryCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByPrimaryKeySelective(Category record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_category
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByPrimaryKey(Category record);
}