package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.City;
import net.cominfo.digiagent.persistence.domain.CityCriteria;

public interface CityDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_city
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	int countByExample(CityCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_city
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	int deleteByExample(CityCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_city
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	int deleteByPrimaryKey(Integer cityId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_city
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	void insert(City record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_city
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	void insertSelective(City record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_city
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	List<City> selectByExample(CityCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_city
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	City selectByPrimaryKey(Integer cityId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_city
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	int updateByExampleSelective(City record, CityCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_city
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	int updateByExample(City record, CityCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_city
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	int updateByPrimaryKeySelective(City record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_city
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	int updateByPrimaryKey(City record);
}