package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.CommodityImage;
import net.cominfo.digiagent.persistence.domain.CommodityImageCriteria;

public interface CommodityImageDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int countByExample(CommodityImageCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int deleteByExample(CommodityImageCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int deleteByPrimaryKey(Integer commodityimageId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	void insert(CommodityImage record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	void insertSelective(CommodityImage record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	List<CommodityImage> selectByExampleWithBLOBs(CommodityImageCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	List<CommodityImage> selectByExampleWithoutBLOBs(
			CommodityImageCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	CommodityImage selectByPrimaryKey(Integer commodityimageId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByExampleSelective(CommodityImage record,
			CommodityImageCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByExampleWithBLOBs(CommodityImage record,
			CommodityImageCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByExampleWithoutBLOBs(CommodityImage record,
			CommodityImageCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByPrimaryKeySelective(CommodityImage record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByPrimaryKeyWithBLOBs(CommodityImage record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByPrimaryKeyWithoutBLOBs(CommodityImage record);
}