package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.CommodityImage;
import net.cominfo.digiagent.persistence.domain.CommodityImageCriteria;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CommodityImageDAOImpl extends BaseDao implements CommodityImageDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	public CommodityImageDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	public int countByExample(CommodityImageCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_da_commodityimage.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	public int deleteByExample(CommodityImageCriteria example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_da_commodityimage.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	public int deleteByPrimaryKey(Integer commodityimageId) {
		CommodityImage key = new CommodityImage();
		key.setCommodityimageId(commodityimageId);
		int rows = getSqlMapClientTemplate().delete(
				"t_da_commodityimage.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	public void insert(CommodityImage record) {
		getSqlMapClientTemplate().insert(
				"t_da_commodityimage.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	public void insertSelective(CommodityImage record) {
		getSqlMapClientTemplate().insert(
				"t_da_commodityimage.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	@SuppressWarnings("unchecked")
	public List<CommodityImage> selectByExampleWithBLOBs(
			CommodityImageCriteria example) {
		List<CommodityImage> list = getSqlMapClientTemplate().queryForList(
				"t_da_commodityimage.ibatorgenerated_selectByExampleWithBLOBs",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	@SuppressWarnings("unchecked")
	public List<CommodityImage> selectByExampleWithoutBLOBs(
			CommodityImageCriteria example) {
		List<CommodityImage> list = getSqlMapClientTemplate().queryForList(
				"t_da_commodityimage.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	public CommodityImage selectByPrimaryKey(Integer commodityimageId) {
		CommodityImage key = new CommodityImage();
		key.setCommodityimageId(commodityimageId);
		CommodityImage record = (CommodityImage) getSqlMapClientTemplate()
				.queryForObject(
						"t_da_commodityimage.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	public int updateByExampleSelective(CommodityImage record,
			CommodityImageCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_da_commodityimage.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	public int updateByExampleWithBLOBs(CommodityImage record,
			CommodityImageCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_da_commodityimage.ibatorgenerated_updateByExampleWithBLOBs",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	public int updateByExampleWithoutBLOBs(CommodityImage record,
			CommodityImageCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_da_commodityimage.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	public int updateByPrimaryKeySelective(CommodityImage record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"t_da_commodityimage.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	public int updateByPrimaryKeyWithBLOBs(CommodityImage record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"t_da_commodityimage.ibatorgenerated_updateByPrimaryKeyWithBLOBs",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	public int updateByPrimaryKeyWithoutBLOBs(CommodityImage record) {
		int rows = getSqlMapClientTemplate().update(
				"t_da_commodityimage.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_da_commodityimage
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	private static class UpdateByExampleParms extends CommodityImageCriteria {
		private Object record;

		public UpdateByExampleParms(Object record,
				CommodityImageCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}