package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.Contact;
import net.cominfo.digiagent.persistence.domain.ContactCriteria;

public class ContactDAOImpl extends BaseDao implements ContactDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_contact
	 * @ibatorgenerated  Mon Sep 27 00:16:04 CST 2010
	 */
	public ContactDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_contact
	 * @ibatorgenerated  Mon Sep 27 00:16:04 CST 2010
	 */
	public int countByExample(ContactCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_da_contact.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_contact
	 * @ibatorgenerated  Mon Sep 27 00:16:04 CST 2010
	 */
	public int deleteByExample(ContactCriteria example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_da_contact.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_contact
	 * @ibatorgenerated  Mon Sep 27 00:16:04 CST 2010
	 */
	public int deleteByPrimaryKey(Integer contactId) {
		Contact key = new Contact();
		key.setContactId(contactId);
		int rows = getSqlMapClientTemplate().delete(
				"t_da_contact.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_contact
	 * @ibatorgenerated  Mon Sep 27 00:16:04 CST 2010
	 */
	public void insert(Contact record) {
		getSqlMapClientTemplate().insert("t_da_contact.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_contact
	 * @ibatorgenerated  Mon Sep 27 00:16:04 CST 2010
	 */
	public void insertSelective(Contact record) {
		getSqlMapClientTemplate().insert(
				"t_da_contact.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_contact
	 * @ibatorgenerated  Mon Sep 27 00:16:04 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<Contact> selectByExample(ContactCriteria example) {
		List<Contact> list = getSqlMapClientTemplate().queryForList(
				"t_da_contact.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_contact
	 * @ibatorgenerated  Mon Sep 27 00:16:04 CST 2010
	 */
	public Contact selectByPrimaryKey(Integer contactId) {
		Contact key = new Contact();
		key.setContactId(contactId);
		Contact record = (Contact) getSqlMapClientTemplate().queryForObject(
				"t_da_contact.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_contact
	 * @ibatorgenerated  Mon Sep 27 00:16:04 CST 2010
	 */
	public int updateByExampleSelective(Contact record, ContactCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_da_contact.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_contact
	 * @ibatorgenerated  Mon Sep 27 00:16:04 CST 2010
	 */
	public int updateByExample(Contact record, ContactCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_da_contact.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_contact
	 * @ibatorgenerated  Mon Sep 27 00:16:04 CST 2010
	 */
	public int updateByPrimaryKeySelective(Contact record) {
		int rows = getSqlMapClientTemplate().update(
				"t_da_contact.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_contact
	 * @ibatorgenerated  Mon Sep 27 00:16:04 CST 2010
	 */
	public int updateByPrimaryKey(Contact record) {
		int rows = getSqlMapClientTemplate().update(
				"t_da_contact.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_da_contact
	 * @ibatorgenerated  Mon Sep 27 00:16:04 CST 2010
	 */
	private static class UpdateByExampleParms extends ContactCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, ContactCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}