package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.Product;
import net.cominfo.digiagent.persistence.domain.ProductCriteria;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ProductDAOImpl extends BaseDao implements ProductDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public ProductDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public int countByExample(ProductCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_da_product.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public int deleteByExample(ProductCriteria example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_da_product.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public int deleteByPrimaryKey(Integer productId) {
		Product key = new Product();
		key.setProductId(productId);
		int rows = getSqlMapClientTemplate().delete(
				"t_da_product.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public void insert(Product record) {
		getSqlMapClientTemplate().insert("t_da_product.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public void insertSelective(Product record) {
		getSqlMapClientTemplate().insert(
				"t_da_product.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<Product> selectByExample(ProductCriteria example) {
		List<Product> list = getSqlMapClientTemplate().queryForList(
				"t_da_product.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public Product selectByPrimaryKey(Integer productId) {
		Product key = new Product();
		key.setProductId(productId);
		Product record = (Product) getSqlMapClientTemplate().queryForObject(
				"t_da_product.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public int updateByExampleSelective(Product record, ProductCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_da_product.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public int updateByExample(Product record, ProductCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_da_product.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public int updateByPrimaryKeySelective(Product record) {
		int rows = getSqlMapClientTemplate().update(
				"t_da_product.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	public int updateByPrimaryKey(Product record) {
		int rows = getSqlMapClientTemplate().update(
				"t_da_product.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_da_product
	 * @ibatorgenerated  Tue Sep 14 18:50:40 CST 2010
	 */
	private static class UpdateByExampleParms extends ProductCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, ProductCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}