package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.ProductBrand;
import net.cominfo.digiagent.persistence.domain.ProductBrandCriteria;

public interface ProductBrandDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_productbrand
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	int countByExample(ProductBrandCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_productbrand
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	int deleteByExample(ProductBrandCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_productbrand
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	int deleteByPrimaryKey(Integer productbrandId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_productbrand
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	void insert(ProductBrand record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_productbrand
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	void insertSelective(ProductBrand record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_productbrand
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	List<ProductBrand> selectByExample(ProductBrandCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_productbrand
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	ProductBrand selectByPrimaryKey(Integer productbrandId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_productbrand
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	int updateByExampleSelective(ProductBrand record,
			ProductBrandCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_productbrand
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	int updateByExample(ProductBrand record, ProductBrandCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_productbrand
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	int updateByPrimaryKeySelective(ProductBrand record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_productbrand
	 * @ibatorgenerated  Sat Aug 14 12:47:37 CST 2010
	 */
	int updateByPrimaryKey(ProductBrand record);
}