package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.Role;
import net.cominfo.digiagent.persistence.domain.RoleCriteria;

public interface RoleDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int countByExample(RoleCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int deleteByExample(RoleCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int deleteByPrimaryKey(Integer roleId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	void insert(Role record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	void insertSelective(Role record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	List<Role> selectByExample(RoleCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	Role selectByPrimaryKey(Integer roleId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByExampleSelective(Role record, RoleCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByExample(Role record, RoleCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByPrimaryKeySelective(Role record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sun Apr 10 20:46:03 CST 2011
	 */
	int updateByPrimaryKey(Role record);
}