package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.Role;
import net.cominfo.digiagent.persistence.domain.RoleCriteria;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RoleDAOImpl extends BaseDao implements RoleDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public RoleDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int countByExample(RoleCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_da_role.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int deleteByExample(RoleCriteria example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_da_role.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int deleteByPrimaryKey(Integer roleId) {
		Role key = new Role();
		key.setRoleId(roleId);
		int rows = getSqlMapClientTemplate().delete(
				"t_da_role.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public void insert(Role record) {
		getSqlMapClientTemplate().insert("t_da_role.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public void insertSelective(Role record) {
		getSqlMapClientTemplate().insert(
				"t_da_role.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<Role> selectByExample(RoleCriteria example) {
		List<Role> list = getSqlMapClientTemplate().queryForList(
				"t_da_role.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public Role selectByPrimaryKey(Integer roleId) {
		Role key = new Role();
		key.setRoleId(roleId);
		Role record = (Role) getSqlMapClientTemplate().queryForObject(
				"t_da_role.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int updateByExampleSelective(Role record, RoleCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_da_role.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int updateByExample(Role record, RoleCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_da_role.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int updateByPrimaryKeySelective(Role record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"t_da_role.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_role
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int updateByPrimaryKey(Role record) {
		int rows = getSqlMapClientTemplate().update(
				"t_da_role.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_da_role
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	private static class UpdateByExampleParms extends RoleCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, RoleCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}