package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.Sequence;
import net.cominfo.digiagent.persistence.domain.SequenceCriteria;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SequenceDAOImpl extends BaseDao implements SequenceDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_sequence
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public SequenceDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_sequence
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int countByExample(SequenceCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_da_sequence.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_sequence
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int deleteByExample(SequenceCriteria example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_da_sequence.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_sequence
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int deleteByPrimaryKey(String name) {
		Sequence key = new Sequence();
		key.setName(name);
		int rows = getSqlMapClientTemplate().delete(
				"t_da_sequence.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_sequence
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public void insert(Sequence record) {
		getSqlMapClientTemplate().insert(
				"t_da_sequence.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_sequence
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public void insertSelective(Sequence record) {
		getSqlMapClientTemplate().insert(
				"t_da_sequence.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_sequence
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<Sequence> selectByExample(SequenceCriteria example) {
		List<Sequence> list = getSqlMapClientTemplate().queryForList(
				"t_da_sequence.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_sequence
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public Sequence selectByPrimaryKey(String name) {
		Sequence key = new Sequence();
		key.setName(name);
		Sequence record = (Sequence) getSqlMapClientTemplate().queryForObject(
				"t_da_sequence.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_sequence
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int updateByExampleSelective(Sequence record,
			SequenceCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"t_da_sequence.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_sequence
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int updateByExample(Sequence record, SequenceCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_da_sequence.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_sequence
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int updateByPrimaryKeySelective(Sequence record) {
		int rows = getSqlMapClientTemplate().update(
				"t_da_sequence.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_sequence
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int updateByPrimaryKey(Sequence record) {
		int rows = getSqlMapClientTemplate().update(
				"t_da_sequence.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_da_sequence
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	private static class UpdateByExampleParms extends SequenceCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, SequenceCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}