package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.Supplier;
import net.cominfo.digiagent.persistence.domain.SupplierCriteria;
import net.cominfo.digiagent.persistence.domain.SupplierWithBLOBs;

public interface SupplierDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_supplier
	 * @ibatorgenerated  Wed Oct 06 11:10:02 CST 2010
	 */
	int countByExample(SupplierCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_supplier
	 * @ibatorgenerated  Wed Oct 06 11:10:02 CST 2010
	 */
	int deleteByExample(SupplierCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_supplier
	 * @ibatorgenerated  Wed Oct 06 11:10:02 CST 2010
	 */
	int deleteByPrimaryKey(Integer supplierId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_supplier
	 * @ibatorgenerated  Wed Oct 06 11:10:02 CST 2010
	 */
	void insert(SupplierWithBLOBs record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_supplier
	 * @ibatorgenerated  Wed Oct 06 11:10:02 CST 2010
	 */
	void insertSelective(SupplierWithBLOBs record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_supplier
	 * @ibatorgenerated  Wed Oct 06 11:10:02 CST 2010
	 */
	List<SupplierWithBLOBs> selectByExampleWithBLOBs(SupplierCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_supplier
	 * @ibatorgenerated  Wed Oct 06 11:10:02 CST 2010
	 */
	List<Supplier> selectByExampleWithoutBLOBs(SupplierCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_supplier
	 * @ibatorgenerated  Wed Oct 06 11:10:02 CST 2010
	 */
	SupplierWithBLOBs selectByPrimaryKey(Integer supplierId);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_supplier
	 * @ibatorgenerated  Wed Oct 06 11:10:02 CST 2010
	 */
	int updateByExampleSelective(SupplierWithBLOBs record,
			SupplierCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_supplier
	 * @ibatorgenerated  Wed Oct 06 11:10:02 CST 2010
	 */
	int updateByExample(SupplierWithBLOBs record, SupplierCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_supplier
	 * @ibatorgenerated  Wed Oct 06 11:10:02 CST 2010
	 */
	int updateByExample(Supplier record, SupplierCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_supplier
	 * @ibatorgenerated  Wed Oct 06 11:10:02 CST 2010
	 */
	int updateByPrimaryKeySelective(SupplierWithBLOBs record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_supplier
	 * @ibatorgenerated  Wed Oct 06 11:10:02 CST 2010
	 */
	int updateByPrimaryKey(SupplierWithBLOBs record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_supplier
	 * @ibatorgenerated  Wed Oct 06 11:10:02 CST 2010
	 */
	int updateByPrimaryKey(Supplier record);
}