package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.SupplierProductCriteria;
import net.cominfo.digiagent.persistence.domain.SupplierProductKey;

public interface SupplierProductDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_supplierproduct
     *
     * @ibatorgenerated Tue Sep 14 19:01:20 CST 2010
     */
    int countByExample(SupplierProductCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_supplierproduct
     *
     * @ibatorgenerated Tue Sep 14 19:01:20 CST 2010
     */
    int deleteByExample(SupplierProductCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_supplierproduct
     *
     * @ibatorgenerated Tue Sep 14 19:01:20 CST 2010
     */
    int deleteByPrimaryKey(SupplierProductKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_supplierproduct
     *
     * @ibatorgenerated Tue Sep 14 19:01:20 CST 2010
     */
    void insert(SupplierProductKey record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_supplierproduct
     *
     * @ibatorgenerated Tue Sep 14 19:01:20 CST 2010
     */
    void insertSelective(SupplierProductKey record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_supplierproduct
     *
     * @ibatorgenerated Tue Sep 14 19:01:20 CST 2010
     */
    List<SupplierProductKey> selectByExample(SupplierProductCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_supplierproduct
     *
     * @ibatorgenerated Tue Sep 14 19:01:20 CST 2010
     */
    int updateByExampleSelective(SupplierProductKey record, SupplierProductCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_da_supplierproduct
     *
     * @ibatorgenerated Tue Sep 14 19:01:20 CST 2010
     */
    int updateByExample(SupplierProductKey record, SupplierProductCriteria example);
}