package net.cominfo.digiagent.persistence.sqlmapdao;

import java.util.List;
import net.cominfo.digiagent.persistence.domain.User;
import net.cominfo.digiagent.persistence.domain.UserCriteria;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserDAOImpl extends BaseDao implements UserDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_user
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public UserDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_user
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int countByExample(UserCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_da_user.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_user
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int deleteByExample(UserCriteria example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_da_user.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_user
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int deleteByPrimaryKey(Integer userId) {
		User key = new User();
		key.setUserId(userId);
		int rows = getSqlMapClientTemplate().delete(
				"t_da_user.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_user
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public void insert(User record) {
		getSqlMapClientTemplate().insert("t_da_user.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_user
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public void insertSelective(User record) {
		getSqlMapClientTemplate().insert(
				"t_da_user.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_user
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<User> selectByExample(UserCriteria example) {
		List<User> list = getSqlMapClientTemplate().queryForList(
				"t_da_user.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_user
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public User selectByPrimaryKey(Integer userId) {
		User key = new User();
		key.setUserId(userId);
		User record = (User) getSqlMapClientTemplate().queryForObject(
				"t_da_user.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_user
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int updateByExampleSelective(User record, UserCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_da_user.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_user
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int updateByExample(User record, UserCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_da_user.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_user
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int updateByPrimaryKeySelective(User record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"t_da_user.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_da_user
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	public int updateByPrimaryKey(User record) {
		int rows = getSqlMapClientTemplate().update(
				"t_da_user.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_da_user
	 * @ibatorgenerated  Sat Oct 09 22:21:31 CST 2010
	 */
	private static class UpdateByExampleParms extends UserCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, UserCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}