package name.huangzhoujin.mymaven.persistence.sqlmapdao;

import java.util.List;
import name.huangzhoujin.mymaven.persistence.domain.Repository;
import name.huangzhoujin.mymaven.persistence.domain.RepositoryExample;
import org.apache.ibatis.annotations.Param;

public interface RepositoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MVN_REPOSITORY
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    int countByExample(RepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MVN_REPOSITORY
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    int deleteByExample(RepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MVN_REPOSITORY
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    int deleteByPrimaryKey(Integer repId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MVN_REPOSITORY
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    int insert(Repository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MVN_REPOSITORY
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    int insertSelective(Repository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MVN_REPOSITORY
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    List<Repository> selectByExample(RepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MVN_REPOSITORY
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    Repository selectByPrimaryKey(Integer repId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MVN_REPOSITORY
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    int updateByExampleSelective(@Param("record") Repository record, @Param("example") RepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MVN_REPOSITORY
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    int updateByExample(@Param("record") Repository record, @Param("example") RepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MVN_REPOSITORY
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    int updateByPrimaryKeySelective(Repository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MVN_REPOSITORY
     *
     * @mbggenerated Fri Feb 01 21:19:42 CST 2013
     */
    int updateByPrimaryKey(Repository record);
}