package name.huangzhoujin.mymaven.utils.spring;

public class BeanConfigurationException extends java.lang.RuntimeException {

	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 6904304538767823730L;

	/**
	 * Creates a new instance of <code>BeanConfigurationException</code> without
	 * detail message.
	 */
	public BeanConfigurationException() {
	}

	/**
	 * Constructs an instance of <code>BeanConfigurationException</code> with
	 * the specified detail message.
	 * 
	 * @param msg
	 *            the detail message.
	 */
	public BeanConfigurationException(String msg) {
		super(msg);
	}

}
