package name.huangzhoujin.registration.persistence.sqlmapdao;

import java.util.List;
import name.huangzhoujin.registration.persistence.domain.Education;
import name.huangzhoujin.registration.persistence.domain.EducationCriteria;
import org.apache.ibatis.annotations.Param;

public interface EducationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_education
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int countByExample(EducationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_education
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int deleteByExample(EducationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_education
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int deleteByPrimaryKey(Integer educationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_education
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int insert(Education record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_education
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int insertSelective(Education record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_education
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    List<Education> selectByExample(EducationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_education
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    Education selectByPrimaryKey(Integer educationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_education
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int updateByExampleSelective(@Param("record") Education record, @Param("example") EducationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_education
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int updateByExample(@Param("record") Education record, @Param("example") EducationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_education
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int updateByPrimaryKeySelective(Education record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_education
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int updateByPrimaryKey(Education record);
}