package name.huangzhoujin.registration.persistence.sqlmapdao;

import java.util.List;
import name.huangzhoujin.registration.persistence.domain.Level;
import name.huangzhoujin.registration.persistence.domain.LevelCriteria;
import org.apache.ibatis.annotations.Param;

public interface LevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_level
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int countByExample(LevelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_level
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int deleteByExample(LevelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_level
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int deleteByPrimaryKey(Integer levelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_level
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int insert(Level record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_level
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int insertSelective(Level record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_level
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    List<Level> selectByExample(LevelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_level
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    Level selectByPrimaryKey(Integer levelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_level
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int updateByExampleSelective(@Param("record") Level record, @Param("example") LevelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_level
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int updateByExample(@Param("record") Level record, @Param("example") LevelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_level
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int updateByPrimaryKeySelective(Level record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_level
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int updateByPrimaryKey(Level record);
}