package name.huangzhoujin.registration.persistence.sqlmapdao;

import java.util.List;
import name.huangzhoujin.registration.persistence.domain.Location;
import name.huangzhoujin.registration.persistence.domain.LocationCriteria;
import org.apache.ibatis.annotations.Param;

public interface LocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_location
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int countByExample(LocationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_location
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int deleteByExample(LocationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_location
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int deleteByPrimaryKey(Integer locationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_location
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int insert(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_location
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int insertSelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_location
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    List<Location> selectByExample(LocationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_location
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    Location selectByPrimaryKey(Integer locationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_location
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int updateByExampleSelective(@Param("record") Location record, @Param("example") LocationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_location
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int updateByExample(@Param("record") Location record, @Param("example") LocationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_location
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int updateByPrimaryKeySelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_location
     *
     * @mbggenerated Sun Jun 03 01:05:59 CST 2012
     */
    int updateByPrimaryKey(Location record);
}