package name.huangzhoujin.registration.persistence.sqlmapdao;

import java.util.List;
import name.huangzhoujin.registration.persistence.domain.Registration;
import name.huangzhoujin.registration.persistence.domain.RegistrationCriteria;
import org.apache.ibatis.annotations.Param;

public interface RegistrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_registration
     *
     * @mbggenerated Tue Jun 26 00:02:33 CST 2012
     */
    int countByExample(RegistrationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_registration
     *
     * @mbggenerated Tue Jun 26 00:02:33 CST 2012
     */
    int deleteByExample(RegistrationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_registration
     *
     * @mbggenerated Tue Jun 26 00:02:33 CST 2012
     */
    int deleteByPrimaryKey(Integer registrationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_registration
     *
     * @mbggenerated Tue Jun 26 00:02:33 CST 2012
     */
    int insert(Registration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_registration
     *
     * @mbggenerated Tue Jun 26 00:02:33 CST 2012
     */
    int insertSelective(Registration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_registration
     *
     * @mbggenerated Tue Jun 26 00:02:33 CST 2012
     */
    List<Registration> selectByExample(RegistrationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_registration
     *
     * @mbggenerated Tue Jun 26 00:02:33 CST 2012
     */
    Registration selectByPrimaryKey(Integer registrationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_registration
     *
     * @mbggenerated Tue Jun 26 00:02:33 CST 2012
     */
    int updateByExampleSelective(@Param("record") Registration record, @Param("example") RegistrationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_registration
     *
     * @mbggenerated Tue Jun 26 00:02:33 CST 2012
     */
    int updateByExample(@Param("record") Registration record, @Param("example") RegistrationCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_registration
     *
     * @mbggenerated Tue Jun 26 00:02:33 CST 2012
     */
    int updateByPrimaryKeySelective(Registration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_registration
     *
     * @mbggenerated Tue Jun 26 00:02:33 CST 2012
     */
    int updateByPrimaryKey(Registration record);
}