package name.huangzhoujin.registration.persistence.sqlmapdao;

import java.util.List;
import name.huangzhoujin.registration.persistence.domain.User;
import name.huangzhoujin.registration.persistence.domain.UserCriteria;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_user
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    int countByExample(UserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_user
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    int deleteByExample(UserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_user
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_user
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_user
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_user
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    List<User> selectByExample(UserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_user
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_user
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_user
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    int updateByExample(@Param("record") User record, @Param("example") UserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_user
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reg_user
     *
     * @mbggenerated Wed Jun 13 18:59:04 CST 2012
     */
    int updateByPrimaryKey(User record);
}